config/routes.rb
Rails.application.routes.draw do
  # get 'customers/index'
  # get 'customers/alphabetized'
  # get 'customers/missing_email'

  resources :customers do
    collection do
      get "alphabetized"
      get "missing_email"
    end
  end

  root to: "customers#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  validates :full_name, :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(:full_name)
  end

  def missing_email
    @customers = Customer.where("email = ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer-card">
  <h2><%= customer.full_name %></h2>
  <p><%= image_tag customer.image if customer.image.attached? %></p>
  <p><%= customer.phone_number %></p>
  <p><%= customer.email %></p>
</div>

app/views/customers/alphabetized.html.erb
<h1>All Customers Ordered Alphabetically</h1>

<div class="customer-grid">
<% @customers.each do |customer| %>

<%= render partial: 'customer', locals: { customer: customer } %>

<% end %>
</div>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<div class="customer-grid">
<% @customers.each do |customer| %>

<%= render partial: 'customer', locals: { customer: customer } %>

<% end %>
</div>

app/views/customers/missing_email.html.erb
<h1>All Customers without Email</h1>

<div class="customer-grid">
<% @customers.each do |customer| %>

<%= render partial: 'customer', locals: { customer: customer } %>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerRelationManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="links">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Alphabetized', alphabetized_customers_path %></li>
        <li><%= link_to 'Missing Email', missing_email_customers_path %></li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>